#!/bin/bash

getHelp(){
	echo 'Descripcion: Este script hace dado un directorio, busca los archivos que tengan uno o ma espacios 
	en sus nombres y los remplaza por el _ y devuelve la cantidad de archivos que se modificaron su nombre '
	echo 'Nombre: ./Ejer2.sh <DirectorioParametro>'
	echo 'Parametro: <DirectorioParametro> ---Es el directorio donde voy a buscar los archivos con espacios'
	echo 'Ejemplo: ./Ejer2.sh Escritorio'
	exit

}

validarCantidadParametros(){

	if($# -eq 0)
	then 
		directAct=$pwd
		exit 1
	fi
			
	if($# -ne 1)
	then 
		echo 'La cantidad de parametro no es correcta'
		echo 'Utilizar la ayuda con -h/-?/-help para mayor informacion'
		exit 1
	fi

	if($1='-h' -o $1='-?' -o $1='-help')
	then 
		getHelp
	exit 1
	fi

}
